### ISSUE TITLE
Validation of rounding on amount of asset input fields is not working properly

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#120]
**Description:**
Unnecessary tooltips are shown while hovering over filters on "Transactions" page.

**Reproduction steps:**
1. Go to Kwenta exchange (https://kwenta.io/exchange)
2. Select any asset (for example `123 sUSD`) inside "From" input field
3. Select any asset (for example `sETH`) inside "Into" input field

**Actual result:**
User is unable to trade with "Please select a valid value" error.

**Expected result:**
No error should be shown in this case.

**Environment:**
MacBook Pro (15-inch), macOS 10.15.6, Chrome 85.0.4183.121

**Screenshots / videos:**
<img width="1377" alt="Screenshot 2020-10-19 at 12 47 21" src="https://user-images.githubusercontent.com/8177587/96520774-11d8f380-1270-11eb-874e-ad9f56a4405b.png">

**Comment by evgenyboxer** [comment]
is this still happening on dev?

**Comment by drptbl** [comment]
@evgenyboxer fixed 🎉
