### ISSUE TITLE
1inch svg is not loading on "Convert" page

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#121]
**Description:**
1inch svg is not loading on "Convert" page

**Reproduction steps:**
1. Go to Kwenta convert page (https://kwenta.eth.link/dashboard/?tab=convert)
2. Connect wallet
3. Type any amount inside "From ETH" input field
4. Click on "Submit Order"

**Actual result:**
1inch svg is not loading on "Convert" page.

**Environment:**
MacBook Pro (15-inch), macOS 10.15.6, Chrome 85.0.4183.121

**Screenshots / videos:**
<img width="1680" alt="Screenshot 2020-10-20 at 01 10 29" src="https://user-images.githubusercontent.com/8177587/96521505-bc054b00-1271-11eb-8686-974800cb94c7.png">

**Comment by evgenyboxer** [comment]
This is a duplicate of #122 right?

**Comment by drptbl** [comment]
Seems fixed.
