### ISSUE TITLE
Login methods other than metamask doesn't seem to work

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#122]
**Description:**
Login methods other than metamask doesn't seem to work

**Reproduction steps:**
1. Go to Kwenta exchange (https://kwenta.eth.link/exchange/)
2. Connect any other wallet than metamask

**Actual result:**
Only metamask login method works.

**Expected result:**
All login methods should work.

**Environment:**
MacBook Pro (15-inch), macOS 10.15.6, Chrome 85.0.4183.121

**Screenshots / videos:**
![2020-10-20 11 31 13](https://user-images.githubusercontent.com/8177587/96572029-a5d8a880-12cc-11eb-962f-85c1b2372ec7.gif)

**Comment by drptbl** [comment]
chunk for walletlink:
https://kwenta.eth.link/_next/static/chunks/27.8184907ec03726616108.js

<img width="841" alt="Screenshot 2020-10-20 at 12 25 00" src="https://user-images.githubusercontent.com/8177587/96574313-9313a300-12cf-11eb-9a1c-ed8fc0ec3b96.png">
<img width="632" alt="Screenshot 2020-10-20 at 12 25 06" src="https://user-images.githubusercontent.com/8177587/96574324-9870ed80-12cf-11eb-94e8-50bdc2cf240a.png">

**Comment by evgenyboxer** [comment]
can we close this?

**Comment by drptbl** [comment]
Yeah, it doesn't happen if IPFS is well populated.
