### ISSUE TITLE
Kwenta UI shows unexpected error on submit trade

### ISSUE THREAD

**Issue by nicholasamiller** [Synthetixio/kwenta#139]
![image](https://user-images.githubusercontent.com/20632432/98495590-95946780-2293-11eb-95fd-03ff3580a1d1.png)

![image](https://user-images.githubusercontent.com/20632432/98495667-cffe0480-2293-11eb-9526-7f3a7d59be9b.png)

I was able to do my trade via the synthetix.exchange, using same browser and wallet.

**Comment by drptbl** [comment]
@nicholasamiller You can track this one in #141 👍.
