### ISSUE TITLE
Fix 1inch on-ramp to include proper quotes and offer any token to sUSD functionality

### ISSUE THREAD

**Issue by Andrew-Synthetix** [Synthetixio/kwenta#247]
Currently, the 1inch on-ramp is disabled as it was showing inaccurate price quotes and causing users to unknowingly lose funds to slippage. 

To fix this, the 1inch on-ramp should be usable without leaving Kwenta and must include accurate quotes, showing the associated slippage with trades via 1inch as necessary.

1inch also offers any cryptocurrency to sUSD, we should include this functionality in the update.

NOTES:

See: https://www.npmjs.com/package/@0xsequence/multicall

- [x] Do a full revamp of 1inch integration + all the slippage information 
- [ ] Add support for any ERC20 token (not just ETH-sUSD)

**Comment by drptbl** [comment]
Created new task for this one:
https://github.com/Synthetixio/issues/issues/13
