### ISSUE TITLE
Enable users to view Synth prices for all assets on the input side, even when a wallet is not yet connected

### ISSUE THREAD

**Issue by Andrew-Synthetix** [Synthetixio/kwenta#252]
Users should be able to see the price of all assets on the "sell" side even when they have not logged in.

- [x] Design Conversation
- [x] Design
- [x] Development

**Comment by evgenyboxer** [comment]
@Andrew-Synthetix the "sell" (or "from") side can only show assets that the user has, so they must be connected.

**Comment by Andrew-Synthetix** [comment]
@evgenyboxer can we change that? We want it to be more like Uniswap where a user can select any token to see prices.
