### ISSUE TITLE
Add stats into Kwenta Shorting UI

### ISSUE THREAD

**Issue by zoe-archer** [Synthetixio/kwenta#273]
The shorting UI needs a sidebar that shows the rewards APR and open interest

Requirements

- [x] Design @zoe-archer (link here)
- [x] Development @evgenyboxer 

<img width="396" alt="CleanShot_2021-03-10_at_09 47 042x" src="https://user-images.githubusercontent.com/46664538/110550108-2e29ee00-8187-11eb-8817-8cfb7e77b193.png">

**Comment by andytcf** [comment]
LGTM closing #274 
![image](https://user-images.githubusercontent.com/39738607/111560594-e8080680-87e6-11eb-9602-e488dc1ccd52.png)
