### ISSUE TITLE
Converting synths to sUSD should be done directly through Kwenta

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#327]
**Description:**
When you select any synth to convert to sUSD, it's done through 1inch, however it should be done directly through Synthetix contracts or synths should be filtered out from "Convert" feature to force users to use Kwenta instead (lower fees).

https://etherscan.io/tx/0x5f6c3c0b6adaffb4784d23dff801e563af544a5d213dafdfd22dda10ef96d283
https://etherscan.io/tx/0xee5a13e25648aaefbd165e308680be6e53fb37a24bba7ab8b181fedfe83d5352

**Prerequisites:**
- any synth on your wallet

**Reproduction steps:**
1. Go to Kwenta "Convert" page (https://dev.kwenta.io/dashboard/convert)
2. Connect your wallet
3. Exchange any synth to sUSD

**Current behavior:**
- synths are exchanged through 1inch which has higher fees than if it would be done directly through Synthetix contracts

**Expected behavior:**
- synths should be exchanged directly through Synthetix contract or they should be filtered out of the list to avoid a case when users burn unnecessary fees

**Screenshots:**
<img width="535" alt="Screenshot 2021-04-12 at 17 29 22" src="https://user-images.githubusercontent.com/8177587/114420653-cb2bdc80-9bb4-11eb-9aee-e76084004e32.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by evgenyboxer** [comment]
Yeah, I agree... its a good enhancement.
