### ISSUE TITLE
Some assets are missing from "Select Token" list on "Convert" page (however they're available on 1inch)

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#329]
**Description:**
Some assets are missing from "Select Token" list on "Convert" page (however they're available on 1inch).

**Prerequisites:**
- missing asset on the wallet (for example "FEI" ERC-20 token => https://www.coingecko.com/en/coins/fei-protocol)

**Reproduction steps:**
1. Go to Kwenta "Convert" page (https://dev.kwenta.io/dashboard/convert)
2. Connect your wallet
3. Open "Select Token" modal

**Current behavior:**
- "FEI" ERC-20 token is missing on the list

**Expected behavior:**
- "FEI" ERC-20 token should be available as it's available on 1inch

**Screenshots:**
<img width="904" alt="Screenshot 2021-04-12 at 17 47 27 1" src="https://user-images.githubusercontent.com/8177587/114423144-2f4fa000-9bb7-11eb-9158-032050104ef0.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by evgenyboxer** [comment]
Seems like their tokenlist was updated a month ago.
@clementbalestrat @andytcf could you guys open a channel with 1inch and ask them how frequently to do update the tokenlist? 

If they don't maintain it anymore... I think it's possible to use something like zerion token list.
