### ISSUE TITLE
Able to set slippage lower than "0.01%" on "Convert" page

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#337]
**Description:**
User is able to set slippage lower than "0.01%" on Kwenta, for example "0.009%".
On 1inch you're not able to set slippage lower than "0.01%" which makes me think it should work the same way on Kwenta.

**Reproduction steps:**
1. Go to Kwenta "Convert" page (https://dev.kwenta.io/dashboard/convert)
2. Connect your wallet
3. Set slippage to "0.009%"

**Current behavior:**
- User is able to set slippage lower than 0.01%.

**Expected behavior:**
- User shouldn't be able to set slippage lower than 0.01%.

**Screenshots:**
<img width="175" alt="Screenshot 2021-04-12 at 22 38 34" src="https://user-images.githubusercontent.com/8177587/114459016-4060d700-9be0-11eb-9519-5002fc38ea56.png">
<img width="1084" alt="Screenshot 2021-04-12 at 22 42 04" src="https://user-images.githubusercontent.com/8177587/114459070-5373a700-9be0-11eb-9dd2-9a6a99af6271.png">
<img width="1564" alt="Screenshot 2021-04-12 at 22 42 56" src="https://user-images.githubusercontent.com/8177587/114459167-7736ed00-9be0-11eb-9de3-8372f2a13439.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

**Comment by JChiaramonte7** [comment]
fixed by #338
