### ISSUE TITLE
Use asset icons inside "Confirm transaction" modal

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#352]
**Description:**
We're showing asset icons inside "Select Token" modal, however we don't do this inside "Confirm transaction" modal. Would be great to have them in both places.

**Screenshots:**
<img width="581" alt="Screenshot 2021-04-22 at 13 16 39" src="https://user-images.githubusercontent.com/8177587/115707685-62402380-a36f-11eb-9ca7-3bf310126411.png">
<img width="1677" alt="Screenshot 2021-04-22 at 13 16 29" src="https://user-images.githubusercontent.com/8177587/115707698-653b1400-a36f-11eb-9468-3b0784713344.png">

**Comment by andytcf** [comment]
PR that fixes this https://github.com/Synthetixio/kwenta/pull/379
