### ISSUE TITLE
Unable to build project after installing npm dependencies without package-lock.json present

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#384]
**Description:**
I'm unable to update repository to node 14 and npm 7 because if you remove `package-lock.json` before installing npm dependencies - you're not able to build the project.

This issue occurs on any node/npm version.

**Reproduction steps:**
1. `git clone https://github.com/Synthetixio/kwenta`
2. `cd kwenta`
3. `rm package-lock.json`
4. `npm install`
5. `npm run build`

**Screenshots:**
<img width="1210" alt="Screenshot_2021-05-28_at_01 22 38" src="https://user-images.githubusercontent.com/8177587/120771232-4a87bd80-c51f-11eb-80f4-bdd60d262dd2.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Chrome 91.0.4472.77

**Comment by vbstreetz** [comment]
I suspect it's a type confict between:
- `node_modules/@ethersproject` (5.1.0/5.30)
- `node_modules/\@synthetixio/contracts-interface/node_modules/\@ethersproject/abstract-provider` (5.0.8)

<img width="874" alt="Screenshot 2021-06-04 at 17 55 59" src="https://user-images.githubusercontent.com/60554509/120821708-665e8400-c55e-11eb-94cd-e24626f2f0de.png">

Possibly a breaking change from 5.0.x to 5.1.x+. I've pushed a fix [here](https://github.com/Synthetixio/js-monorepo/pull/26) to bump the ethers version in monorepo packages to 5.3.+
