### ISSUE TITLE
Add etherscan url for "Your transaction has succeded" notification

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#75]
**Description:**
Add etherscan url for "Your transaction has succeded" notification. Only "Your transaction is pending" opens etherscan transaction page.

<img width="349" alt="Screenshot 2020-10-14 at 17 59 57" src="https://user-images.githubusercontent.com/8177587/96014895-3172b500-0e47-11eb-882d-8dee4973b9d6.png">

**Comment by evgenyboxer** [comment]
Fixed (the whole box is clickable)
