### ISSUE TITLE
Closing a notification which has etherscan url binded opens etherscan transaction page

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#76]
**Description**:
When a notification which opens etherscan transaction page on click is closed with "X" button, it opens etherscan transaction page in addition to closing notification.

![2020-10-14 18 01 50](https://user-images.githubusercontent.com/8177587/96015150-844c6c80-0e47-11eb-8f27-2f73e41b31cf.gif)

**Comment by clementbalestrat** [comment]
I had a chat with the team. They'll be deploying a fix this week :)

**Comment by drptbl** [comment]
Fixed 👍
