### ISSUE TITLE
Hide "Equities" from exchange until we have any available

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/kwenta#82]
**Description:**
Currently we don't have any equities available on exchange, so there is no point in showing empty tabs/filters for them.

**Screenshots:**
<img width="505" alt="Screenshot 2020-10-15 at 01 51 15" src="https://user-images.githubusercontent.com/8177587/96057295-ef6a6300-0e88-11eb-8ac2-b24f669555e5.png">
<img width="1151" alt="Screenshot 2020-10-15 at 01 51 10" src="https://user-images.githubusercontent.com/8177587/96057299-f1ccbd00-0e88-11eb-92f8-500f36951aa0.png">

**Comment by evgenyboxer** [comment]
my bad, after I'll update to the latest `@synthetixio/js` - it will have it.

**Comment by evgenyboxer** [comment]
We can close this - http://kwenta-git-dev.synthetixio.vercel.app/ has equities.

**Comment by drptbl** [comment]
Fixed 👍
