### ISSUE TITLE
Bug: upgrading to v1.0.4 of @synthetixio/js causes Rinkeby to break

### ISSUE THREAD

**Issue by evgenyboxer** [Synthetixio/kwenta#95]
Version 1.0.4 brings in support for Goerli test network + latest Synthetix protocol version.

When I tried to connect to Rinkeby I got the error:

`
Unhandled Runtime Error
Error: cannot have constant function with mutability view (argument="value", value={"constant":false,"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"issue","outputs":[],"payable":false,"stateMutability":"view","type":"function","signature":"0x867904b4"}, code=INVALID_ARGUMENT, version=abi/5.0.2)
`

@justinjmoses thinks this is an ABI issue.

Will investigate with @dvd-schwrtz

**Comment by justinjmoses** [comment]
Fixed with: https://github.com/Synthetixio/synthetix/commit/32b3a1095996993ca10b55d2d929e1f14721c44a 

It will need another release of synthetix however. Do you need one?

**Comment by evgenyboxer** [comment]
Yes please, that would be great 👍
